<div class="root">
  <div class="loadingio-spinner-rolling-pxmrq34tc2">
    <div class="ldio-935u5yb122">
      <div />
    </div>
  </div>
</div>

<style>
  .root {
    width: 100%;
    display: flex;
    justify-content: center;
  }
  @keyframes ldio-935u5yb122 {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
  .ldio-935u5yb122 div {
    position: absolute;
    width: 97.34px;
    height: 97.34px;
    border: 12.56px solid #df1317;
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-935u5yb122 div {
    animation: ldio-935u5yb122 1s linear infinite;
    top: 78.5px;
    left: 78.5px;
  }
  .loadingio-spinner-rolling-pxmrq34tc2 {
    width: 157px;
    height: 157px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-935u5yb122 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-935u5yb122 div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
</style>
